production:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_production
    user:         postgres

development:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_development
    user:         postgres

test:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_test
    user:         postgres
